server:
  port: 8080
spring:
  kafka:
    bootstrap-servers: 172.16.33.52:9092,172.16.33.52:9093,172.16.33.52:9094
    producer:
      retries: 3
      acks: 1
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

    consumer:
      group-id: default-group
      enable-auto-commit: false
      auto-offset-reset: earliest


